"""Automated code review logging module."""

import logging
import re
from typing import Optional
from .llm_client import LLMClient
from .github_client import GitHubClient

logger = logging.getLogger(__name__)


class CodeReviewUpdater:
    """Maintains a persistent log of code reviews in CODE_REVIEW.md."""

    # The main code review log file
    LOG_FILE = "CODE_REVIEW.md"

    def __init__(self, github_client: GitHubClient, llm_client: LLMClient):
        """Initialize code review updater.

        Args:
            github_client: GitHub API client
            llm_client: LLM client for analysis
        """
        self.github = github_client
        self.llm = llm_client

    async def update_review_log(self, commit_sha: str, review_content: str, branch: str = "main") -> Optional[str]:
        """Update AUTOMATED_REVIEWS.md with a summary of the latest review.

        Args:
            commit_sha: Commit SHA
            review_content: The full review content generated by CodeReviewer
            branch: Branch to update on

        Returns:
            Updated AUTOMATED_REVIEWS.md content, or None if failed
        """
        logger.info(f"Updating {self.LOG_FILE} for commit {commit_sha}")

        # Fetch current log file
        current_log = await self.github.get_file_content(self.LOG_FILE, ref=branch)
        if current_log is None:
            logger.info(f"{self.LOG_FILE} not found, creating new one")
            current_log = self._create_initial_log()

        # Generate summary entry
        try:
            # LLM now returns tuple (content, metadata)
            entry, usage_metadata = await self.llm.summarize_review(review_content, current_log)
            # Store metadata for later logging
            self._last_usage_metadata = usage_metadata
        except Exception as e:
            logger.error(f"Failed to generate review summary: {e}")
            return None

        if not entry:
            logger.error("Failed to generate review summary entry")
            return None

        # Clean up entry
        entry = self._clean_review_entry(entry)

        # Append to log
        updated_log = current_log.strip() + "\n\n" + entry.strip() + "\n"
        
        return updated_log

    def _create_initial_log(self) -> str:
        """Create initial CODE_REVIEW.md structure."""
        return """# Code Review Report

**Date:** (Auto-generated)
**Reviewer:** GitHub Automation Agent (AI)
**Target:** `src/automation_agent/` and configuration
**Reference Docs:** `AGENTS.md`, `spec.md`, `README.md`

## Review History

"""

    def _clean_review_entry(self, entry: str) -> str:
        """Clean up LLM output to extract pure review entry.

        Args:
            entry: Raw LLM output

        Returns:
            Cleaned review entry
        """
        # Remove markdown code block wrappers if present
        entry = re.sub(r'\A```markdown\s*\n', '', entry)
        entry = re.sub(r'\A```\s*\n', '', entry)
        entry = re.sub(r'\n```\s*\Z', '', entry)
        
        # Remove any leading/trailing whitespace
        entry = entry.strip()
        
        return entry
