"""Automated code review logging module."""

import logging
import re
from typing import Optional
from .llm_client import LLMClient
from .github_client import GitHubClient

logger = logging.getLogger(__name__)


class CodeReviewUpdater:
    """Maintains a persistent log of code reviews in code_review.md."""

    def __init__(self, github_client: GitHubClient, llm_client: LLMClient):
        """Initialize code review updater.

        Args:
            github_client: GitHub API client
            llm_client: LLM client for analysis
        """
        self.github = github_client
        self.llm = llm_client

    async def update_review_log(self, commit_sha: str, review_content: str, branch: str = "main") -> Optional[str]:
        """Update code_review.md with a summary of the latest review.

        Args:
            commit_sha: Commit SHA
            review_content: The full review content generated by CodeReviewer
            branch: Branch to update on

        Returns:
            Updated code_review.md content, or None if failed
        """
        logger.info(f"Updating code_review.md for commit {commit_sha}")

        # Fetch current code_review.md
        current_log = await self.github.get_file_content("code_review.md", ref=branch)
        if current_log is None:
            logger.info("code_review.md not found, creating new one")
            current_log = self._create_initial_log()

        # Generate summary entry
        try:
            entry = await self.llm.summarize_review(review_content, current_log)
        except Exception as e:
            logger.error(f"Failed to generate review summary: {e}")
            return None

        if not entry:
            logger.error("Failed to generate review summary entry")
            return None

        # Clean up entry
        entry = self._clean_review_entry(entry)

        # Append to log
        updated_log = current_log.strip() + "\n\n" + entry.strip() + "\n"
        
        return updated_log

    def _create_initial_log(self) -> str:
        """Create initial code_review.md structure."""
        return """# Code Review Log

This document tracks the history of automated code reviews.

## Review History
"""

    def _clean_review_entry(self, entry: str) -> str:
        """Clean up LLM output to extract pure review entry.

        Args:
            entry: Raw LLM output

        Returns:
            Cleaned review entry
        """
        # Remove markdown code block wrappers if present
        entry = re.sub(r'^```markdown\s*\n', '', entry, flags=re.MULTILINE)
        entry = re.sub(r'^```\s*\n', '', entry, flags=re.MULTILINE)
        entry = re.sub(r'\n```\s*$', '', entry, flags=re.MULTILINE)
        
        # Remove any leading/trailing whitespace
        entry = entry.strip()
        
        return entry
