"""Review provider abstraction for pluggable code review engines."""

import logging
import aiohttp
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
from .llm_client import LLMClient
from .config import Config

logger = logging.getLogger(__name__)


class ReviewProvider(ABC):
    """Abstract base class for code review providers."""

    @abstractmethod
    async def review_code(self, diff: str) -> str:
        """Analyze code changes and provide a review."""
        pass

    @abstractmethod
    async def update_readme(self, diff: str, current_readme: str) -> str:
        """Generate updates for README.md."""
        pass

    @abstractmethod
    async def update_spec(self, commit_info: Dict[str, Any], diff: str, current_spec: str) -> str:
        """Update spec.md based on commit info."""
        pass


class LLMReviewProvider(ReviewProvider):
    """Review provider using the existing LLMClient (Gemini/OpenAI/Anthropic)."""

    def __init__(self, llm_client: LLMClient):
        self.llm = llm_client

    async def review_code(self, diff: str) -> str:
        return await self.llm.analyze_code(diff)

    async def update_readme(self, diff: str, current_readme: str) -> str:
        return await self.llm.update_readme(diff, current_readme)

    async def update_spec(self, commit_info: Dict[str, Any], diff: str, current_spec: str) -> str:
        return await self.llm.update_spec(commit_info, diff, current_spec)


class JulesReviewProvider(ReviewProvider):
    """Review provider using Jules / Google Code Review API with fallback to LLM."""

    def __init__(self, config: Config, fallback_provider: ReviewProvider):
        self.config = config
        self.fallback = fallback_provider
        self.api_key = config.JULES_API_KEY
        self.api_url = config.JULES_API_URL

    async def review_code(self, diff: str) -> str:
        """Review code using Jules API, falling back to LLM on failure."""
        try:
            logger.info("Requesting code review from Jules API...")
            async with aiohttp.ClientSession() as session:
                payload = {
                    "diff": diff,
                    "context": "github_pr"
                }
                headers = {
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json"
                }
                async with session.post(self.api_url, json=payload, headers=headers) as response:
                    if response.status == 200:
                        data = await response.json()
                        review = data.get("review", "")
                        if review:
                            logger.info("Successfully received review from Jules")
                            return self._format_jules_review(review)
                    
                    logger.warning(f"Jules API failed with status {response.status}: {await response.text()}")
                    raise Exception(f"Jules API error: {response.status}")

        except Exception as e:
            logger.warning(f"Jules review failed: {e}. Falling back to LLM provider.")
            return await self.fallback.review_code(diff)

    async def update_readme(self, diff: str, current_readme: str) -> str:
        """Jules does not support README updates yet, using fallback."""
        logger.info("Jules does not support README updates, using fallback.")
        return await self.fallback.update_readme(diff, current_readme)

    async def update_spec(self, commit_info: Dict[str, Any], diff: str, current_spec: str) -> str:
        """Jules does not support Spec updates yet, using fallback."""
        logger.info("Jules does not support Spec updates, using fallback.")
        return await self.fallback.update_spec(commit_info, diff, current_spec)

    def _format_jules_review(self, raw_review: str) -> str:
        """Format Jules output to match our expected markdown structure."""
        # Assuming Jules returns raw markdown or text that needs wrapping
        # This can be adjusted based on actual Jules API response format
        return f"""# 🤖 Jules Code Review

{raw_review}

---
*Generated by Jules / Google Code Review API*
"""
